name: eks deployment
on: workflow_dispatch
jobs:
  eks-deployment:
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Notification
        run: echo "eks deployment process started"
      - name: Checkout
        run: echo " git clone https://github.com/muralialakuntla3/lms-app.git"
      - name: Server Installation
        run: |
          echo "aws cli installed"
          echo "kubectl installed with respect to cluster version"
          echo "docker installed"
      - name: Configure AWS Cli
        run: echo "aws credentials are configure"
      - name: connect to cluster
        run: echo "connected to lms-cluster"
      - name: Databse Setup
        run: |
          echo " cd lms-app/k8s "
          echo " create pg-secret.yml and apply in cluster & kubectl apply -f pg-secret.yml"
          echo "create pg-deployment.yml & kubectl apply -f pg-deployment.yml"
          echo "create pg-service.yml & kubectl apply -f pg-service.yml"
      - name: Backend Setup
        run: |
          echo "build image and push it to docker hub"
          echo "create be-configmap.yml & kubectl apply -f be-configmap.yml"
          echo "create be-deployment.yml & kubectl apply -f be-deployment.yml"
          echo " create be-service.yml & kubectl apply -f be-service.yml"
      - name: Frontend Setup
        run: |
          echo " update BE LB URL in .env file and build the image and push to docker hub"
          echo "create fe-deployment.yml & kubectl apply -f fe-deployment.yml"
          echo " create fe-service.yml & kubectl apply -f fe-service.yml"
      - name: Feedback
        run: echo "all the pods are up and running"
          
      
    
