name: feedback
on: workflow_call
jobs:
  feedback:
    runs-on: ubuntu-latest
    steps:
      - name: send notification
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            channel: project-11
            text: "lms deployed successfully"
